include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  exclude: [build/**, third_party/**, test/version_check/**]
  language:
    strict-raw-types: true

linter:
  rules:
    prefer_final_locals: true
    prefer_const_declarations: true
