// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

typedef AcceptMammal = ffi.Pointer<objc.ObjCBlockImpl>;
typedef DartAcceptMammal = objc.ObjCBlock<ffi.Bool Function(Mammal)>;
typedef AcceptPlatypus = ffi.Pointer<objc.ObjCBlockImpl>;
typedef DartAcceptPlatypus = objc.ObjCBlock<ffi.Bool Function(Platypus)>;

/// BlockInheritTestBase
extension type BlockInheritTestBase._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [BlockInheritTestBase] that points to the same underlying object as [other].
  BlockInheritTestBase.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [BlockInheritTestBase] that wraps the given raw object pointer.
  BlockInheritTestBase.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [BlockInheritTestBase].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_BlockInheritTestBase,
        );

  /// alloc
  static BlockInheritTestBase alloc() {
    final $ret = _objc_msgSend_151sglz(_class_BlockInheritTestBase, _sel_alloc);
    return BlockInheritTestBase.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static BlockInheritTestBase allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_BlockInheritTestBase,
      _sel_allocWithZone_,
      zone,
    );
    return BlockInheritTestBase.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static BlockInheritTestBase new$() {
    final $ret = _objc_msgSend_151sglz(_class_BlockInheritTestBase, _sel_new);
    return BlockInheritTestBase.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of BlockInheritTestBase constructed with the default `new` method.
  BlockInheritTestBase() : this.as(new$().object$);
}

extension BlockInheritTestBase$Methods on BlockInheritTestBase {
  /// acceptAnimal:
  bool acceptAnimal(Platypus platypus) {
    return _objc_msgSend_19nvye5(
      object$.ref.pointer,
      _sel_acceptAnimal_,
      platypus.ref.pointer,
    );
  }

  /// getAccepter
  DartAcceptPlatypus getAccepter() {
    final $ret = _objc_msgSend_uwvaik(object$.ref.pointer, _sel_getAccepter);
    return ObjCBlock_bool_Platypus.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }

  /// getAnimal
  Mammal getAnimal() {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_getAnimal);
    return Mammal.fromPointer($ret, retain: true, release: true);
  }

  /// getReturner
  DartReturnMammal getReturner() {
    final $ret = _objc_msgSend_uwvaik(object$.ref.pointer, _sel_getReturner);
    return ObjCBlock_Mammal.fromPointer($ret, retain: true, release: true);
  }

  /// init
  BlockInheritTestBase init() {
    objc.checkOsVersionInternal(
      'BlockInheritTestBase.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return BlockInheritTestBase.fromPointer($ret, retain: false, release: true);
  }

  /// invokeAccepter:
  bool invokeAccepter(DartAcceptMammal accepter) {
    return _objc_msgSend_z0nr1o(
      object$.ref.pointer,
      _sel_invokeAccepter_,
      accepter.ref.pointer,
    );
  }

  /// invokeReturner:
  Mammal invokeReturner(DartReturnPlatypus returner) {
    final $ret = _objc_msgSend_nnxkei(
      object$.ref.pointer,
      _sel_invokeReturner_,
      returner.ref.pointer,
    );
    return Mammal.fromPointer($ret, retain: true, release: true);
  }
}

/// BlockInheritTestChild
extension type BlockInheritTestChild._(objc.ObjCObject object$)
    implements objc.ObjCObject, BlockInheritTestBase {
  /// Constructs a [BlockInheritTestChild] that points to the same underlying object as [other].
  BlockInheritTestChild.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [BlockInheritTestChild] that wraps the given raw object pointer.
  BlockInheritTestChild.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [BlockInheritTestChild].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_BlockInheritTestChild,
        );

  /// alloc
  static BlockInheritTestChild alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_BlockInheritTestChild,
      _sel_alloc,
    );
    return BlockInheritTestChild.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// allocWithZone:
  static BlockInheritTestChild allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_BlockInheritTestChild,
      _sel_allocWithZone_,
      zone,
    );
    return BlockInheritTestChild.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// new
  static BlockInheritTestChild new$() {
    final $ret = _objc_msgSend_151sglz(_class_BlockInheritTestChild, _sel_new);
    return BlockInheritTestChild.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of BlockInheritTestChild constructed with the default `new` method.
  BlockInheritTestChild() : this.as(new$().object$);
}

extension BlockInheritTestChild$Methods on BlockInheritTestChild {
  /// acceptAnimal:
  bool acceptAnimal(Mammal mammal) {
    return _objc_msgSend_19nvye5(
      object$.ref.pointer,
      _sel_acceptAnimal_,
      mammal.ref.pointer,
    );
  }

  /// getAccepter
  DartAcceptMammal getAccepter() {
    final $ret = _objc_msgSend_uwvaik(object$.ref.pointer, _sel_getAccepter);
    return ObjCBlock_bool_Mammal.fromPointer($ret, retain: true, release: true);
  }

  /// getAnimal
  Platypus getAnimal() {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_getAnimal);
    return Platypus.fromPointer($ret, retain: true, release: true);
  }

  /// getReturner
  DartReturnPlatypus getReturner() {
    final $ret = _objc_msgSend_uwvaik(object$.ref.pointer, _sel_getReturner);
    return ObjCBlock_Platypus.fromPointer($ret, retain: true, release: true);
  }

  /// init
  BlockInheritTestChild init() {
    objc.checkOsVersionInternal(
      'BlockInheritTestChild.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return BlockInheritTestChild.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// invokeAccepter:
  bool invokeAccepter(DartAcceptPlatypus accepter) {
    return _objc_msgSend_z0nr1o(
      object$.ref.pointer,
      _sel_invokeAccepter_,
      accepter.ref.pointer,
    );
  }

  /// invokeReturner:
  Mammal invokeReturner(DartReturnMammal returner) {
    final $ret = _objc_msgSend_nnxkei(
      object$.ref.pointer,
      _sel_invokeReturner_,
      returner.ref.pointer,
    );
    return Mammal.fromPointer($ret, retain: true, release: true);
  }
}

/// Mammal
extension type Mammal._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [Mammal] that points to the same underlying object as [other].
  Mammal.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [Mammal] that wraps the given raw object pointer.
  Mammal.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [Mammal].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_Mammal,
        );

  /// alloc
  static Mammal alloc() {
    final $ret = _objc_msgSend_151sglz(_class_Mammal, _sel_alloc);
    return Mammal.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static Mammal allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_Mammal,
      _sel_allocWithZone_,
      zone,
    );
    return Mammal.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static Mammal new$() {
    final $ret = _objc_msgSend_151sglz(_class_Mammal, _sel_new);
    return Mammal.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of Mammal constructed with the default `new` method.
  Mammal() : this.as(new$().object$);
}

extension Mammal$Methods on Mammal {
  /// init
  Mammal init() {
    objc.checkOsVersionInternal(
      'Mammal.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return Mammal.fromPointer($ret, retain: false, release: true);
  }

  /// laysEggs
  bool laysEggs() {
    return _objc_msgSend_91o635(object$.ref.pointer, _sel_laysEggs);
  }
}

/// Construction methods for `objc.ObjCBlock<Mammal Function()>`.
abstract final class ObjCBlock_Mammal {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<Mammal Function()> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<Mammal Function()>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<Mammal Function()> fromFunctionPointer(
    ffi.Pointer<ffi.NativeFunction<ffi.Pointer<objc.ObjCObjectImpl> Function()>>
    ptr,
  ) => objc.ObjCBlock<Mammal Function()>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<Mammal Function()> fromFunction(
    Mammal Function() fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<Mammal Function()>(
    objc.newClosureBlock(
      _closureCallable,
      () => fn().ref.retainAndAutorelease(),
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  static ffi.Pointer<objc.ObjCObjectImpl> _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
  ) => block.ref.target
      .cast<ffi.NativeFunction<ffi.Pointer<objc.ObjCObjectImpl> Function()>>()
      .asFunction<ffi.Pointer<objc.ObjCObjectImpl> Function()>()();
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
            )
          >(_fnPtrTrampoline)
          .cast();
  static ffi.Pointer<objc.ObjCObjectImpl> _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
  ) =>
      (objc.getBlockClosure(block)
          as ffi.Pointer<objc.ObjCObjectImpl> Function())();
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<Mammal Function()>`.
extension ObjCBlock_Mammal$CallExtension on objc.ObjCBlock<Mammal Function()> {
  Mammal call() => Mammal.fromPointer(
    ref.pointer.ref.invoke
        .cast<
          ffi.NativeFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl> block,
            )
          >
        >()
        .asFunction<
          ffi.Pointer<objc.ObjCObjectImpl> Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
          )
        >()(ref.pointer),
    retain: true,
    release: true,
  );
}

/// Construction methods for `objc.ObjCBlock<Platypus Function()>`.
abstract final class ObjCBlock_Platypus {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<Platypus Function()> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<Platypus Function()>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<Platypus Function()> fromFunctionPointer(
    ffi.Pointer<ffi.NativeFunction<ffi.Pointer<objc.ObjCObjectImpl> Function()>>
    ptr,
  ) => objc.ObjCBlock<Platypus Function()>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<Platypus Function()> fromFunction(
    Platypus Function() fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<Platypus Function()>(
    objc.newClosureBlock(
      _closureCallable,
      () => fn().ref.retainAndAutorelease(),
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  static ffi.Pointer<objc.ObjCObjectImpl> _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
  ) => block.ref.target
      .cast<ffi.NativeFunction<ffi.Pointer<objc.ObjCObjectImpl> Function()>>()
      .asFunction<ffi.Pointer<objc.ObjCObjectImpl> Function()>()();
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
            )
          >(_fnPtrTrampoline)
          .cast();
  static ffi.Pointer<objc.ObjCObjectImpl> _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
  ) =>
      (objc.getBlockClosure(block)
          as ffi.Pointer<objc.ObjCObjectImpl> Function())();
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<Platypus Function()>`.
extension ObjCBlock_Platypus$CallExtension
    on objc.ObjCBlock<Platypus Function()> {
  Platypus call() => Platypus.fromPointer(
    ref.pointer.ref.invoke
        .cast<
          ffi.NativeFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl> block,
            )
          >
        >()
        .asFunction<
          ffi.Pointer<objc.ObjCObjectImpl> Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
          )
        >()(ref.pointer),
    retain: true,
    release: true,
  );
}

/// Construction methods for `objc.ObjCBlock<ffi.Bool Function(Mammal)>`.
abstract final class ObjCBlock_bool_Mammal {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.Bool Function(Mammal)> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.Bool Function(Mammal)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.Bool Function(Mammal)> fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
      >
    >
    ptr,
  ) => objc.ObjCBlock<ffi.Bool Function(Mammal)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Bool Function(Mammal)> fromFunction(
    bool Function(Mammal) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.Bool Function(Mammal)>(
    objc.newClosureBlock(
      _closureCallable,
      (ffi.Pointer<objc.ObjCObjectImpl> arg0) =>
          fn(Mammal.fromPointer(arg0, retain: true, release: true)),
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  static bool _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
        >
      >()
      .asFunction<bool Function(ffi.Pointer<objc.ObjCObjectImpl>)>()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline, false)
          .cast();
  static bool _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) =>
      (objc.getBlockClosure(block)
          as bool Function(ffi.Pointer<objc.ObjCObjectImpl>))(arg0);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline, false)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Bool Function(Mammal)>`.
extension ObjCBlock_bool_Mammal$CallExtension
    on objc.ObjCBlock<ffi.Bool Function(Mammal)> {
  bool call(Mammal arg0) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<objc.ObjCObjectImpl> arg0,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<objc.ObjCBlockImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(ref.pointer, arg0.ref.pointer);
}

/// Construction methods for `objc.ObjCBlock<ffi.Bool Function(Platypus)>`.
abstract final class ObjCBlock_bool_Platypus {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.Bool Function(Platypus)> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.Bool Function(Platypus)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.Bool Function(Platypus)> fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
      >
    >
    ptr,
  ) => objc.ObjCBlock<ffi.Bool Function(Platypus)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Bool Function(Platypus)> fromFunction(
    bool Function(Platypus) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.Bool Function(Platypus)>(
    objc.newClosureBlock(
      _closureCallable,
      (ffi.Pointer<objc.ObjCObjectImpl> arg0) =>
          fn(Platypus.fromPointer(arg0, retain: true, release: true)),
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  static bool _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
        >
      >()
      .asFunction<bool Function(ffi.Pointer<objc.ObjCObjectImpl>)>()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline, false)
          .cast();
  static bool _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) =>
      (objc.getBlockClosure(block)
          as bool Function(ffi.Pointer<objc.ObjCObjectImpl>))(arg0);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline, false)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Bool Function(Platypus)>`.
extension ObjCBlock_bool_Platypus$CallExtension
    on objc.ObjCBlock<ffi.Bool Function(Platypus)> {
  bool call(Platypus arg0) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<objc.ObjCObjectImpl> arg0,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<objc.ObjCBlockImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(ref.pointer, arg0.ref.pointer);
}

/// Platypus
extension type Platypus._(objc.ObjCObject object$)
    implements objc.ObjCObject, Mammal {
  /// Constructs a [Platypus] that points to the same underlying object as [other].
  Platypus.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [Platypus] that wraps the given raw object pointer.
  Platypus.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [Platypus].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_Platypus,
        );

  /// alloc
  static Platypus alloc() {
    final $ret = _objc_msgSend_151sglz(_class_Platypus, _sel_alloc);
    return Platypus.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static Platypus allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_Platypus,
      _sel_allocWithZone_,
      zone,
    );
    return Platypus.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static Platypus new$() {
    final $ret = _objc_msgSend_151sglz(_class_Platypus, _sel_new);
    return Platypus.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of Platypus constructed with the default `new` method.
  Platypus() : this.as(new$().object$);
}

extension Platypus$Methods on Platypus {
  /// init
  Platypus init() {
    objc.checkOsVersionInternal(
      'Platypus.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return Platypus.fromPointer($ret, retain: false, release: true);
  }
}

typedef ReturnMammal = ffi.Pointer<objc.ObjCBlockImpl>;
typedef DartReturnMammal = objc.ObjCBlock<Mammal Function()>;
typedef ReturnPlatypus = ffi.Pointer<objc.ObjCBlockImpl>;
typedef DartReturnPlatypus = objc.ObjCBlock<Platypus Function()>;
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$_BlockInheritTestBase',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class_BlockInheritTestBase_raw;
final _class_BlockInheritTestBase = objc.getClass(
  "BlockInheritTestBase",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_BlockInheritTestBase_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$_BlockInheritTestChild',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class_BlockInheritTestChild_raw;
final _class_BlockInheritTestChild = objc.getClass(
  "BlockInheritTestChild",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_BlockInheritTestChild_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(symbol: 'OBJC_CLASS_\$_Mammal')
external ffi.Pointer<objc.ObjCObjectImpl> _class_Mammal_raw;
final _class_Mammal = objc.getClass(
  "Mammal",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_Mammal_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(symbol: 'OBJC_CLASS_\$_Platypus')
external ffi.Pointer<objc.ObjCObjectImpl> _class_Platypus_raw;
final _class_Platypus = objc.getClass(
  "Platypus",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_Platypus_raw,
  ).cast(),
);
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
final _objc_msgSend_91o635 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_nnxkei = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCBlockImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCBlockImpl>,
      )
    >();
final _objc_msgSend_uwvaik = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCBlockImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCBlockImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_z0nr1o = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCBlockImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCBlockImpl>,
      )
    >();
late final _sel_acceptAnimal_ = objc.registerName("acceptAnimal:");
late final _sel_alloc = objc.registerName("alloc");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
late final _sel_getAccepter = objc.registerName("getAccepter");
late final _sel_getAnimal = objc.registerName("getAnimal");
late final _sel_getReturner = objc.registerName("getReturner");
late final _sel_init = objc.registerName("init");
late final _sel_invokeAccepter_ = objc.registerName("invokeAccepter:");
late final _sel_invokeReturner_ = objc.registerName("invokeReturner:");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
late final _sel_laysEggs = objc.registerName("laysEggs");
late final _sel_new = objc.registerName("new");
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
