// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

/// Tests API deprecation
class DeprecatedTestObjCLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  DeprecatedTestObjCLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  DeprecatedTestObjCLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int normalFunction() {
    return _normalFunction();
  }

  late final _normalFunctionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('normalFunction');
  late final _normalFunction = _normalFunctionPtr.asFunction<int Function()>();
}

@ffi.Native<
  ffi.Int Function(ffi.Pointer<objc.ObjCObjectImpl>, ffi.Pointer<ffi.Void>)
>()
external int _1flqfr_protocolTrampoline_1l0nlq(
  ffi.Pointer<objc.ObjCObjectImpl> target,
  ffi.Pointer<ffi.Void> arg0,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<ffi.Void>,
    ffi.Int,
  )
>()
external void _1flqfr_protocolTrampoline_1t7vjnw(
  ffi.Pointer<objc.ObjCObjectImpl> target,
  ffi.Pointer<ffi.Void> arg0,
  int arg1,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Pointer<objc.ObjCBlockImpl>,
    ffi.Pointer<objc.ObjCBlockImpl>,
    ffi.Pointer<objc.DOBJC_Context>,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _1flqfr_wrapBlockingBlock_1t7vjnw(
  ffi.Pointer<objc.ObjCBlockImpl> block,
  ffi.Pointer<objc.ObjCBlockImpl> listnerBlock,
  ffi.Pointer<objc.DOBJC_Context> context,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(ffi.Pointer<objc.ObjCBlockImpl>)
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _1flqfr_wrapListenerBlock_1t7vjnw(
  ffi.Pointer<objc.ObjCBlockImpl> block,
);

/// DeprecatedInterfaceMethods
extension type DeprecatedInterfaceMethods._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [DeprecatedInterfaceMethods] that points to the same underlying object as [other].
  DeprecatedInterfaceMethods.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [DeprecatedInterfaceMethods] that wraps the given raw object pointer.
  DeprecatedInterfaceMethods.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [DeprecatedInterfaceMethods].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_DeprecatedInterfaceMethods,
  );

  /// alloc
  static DeprecatedInterfaceMethods alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_DeprecatedInterfaceMethods,
      _sel_alloc,
    );
    return DeprecatedInterfaceMethods.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// allocWithZone:
  static DeprecatedInterfaceMethods allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_1cwp428(
      _class_DeprecatedInterfaceMethods,
      _sel_allocWithZone_,
      zone,
    );
    return DeprecatedInterfaceMethods.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// new
  static DeprecatedInterfaceMethods new$() {
    final $ret = _objc_msgSend_151sglz(
      _class_DeprecatedInterfaceMethods,
      _sel_new,
    );
    return DeprecatedInterfaceMethods.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of DeprecatedInterfaceMethods constructed with the default `new` method.
  DeprecatedInterfaceMethods() : this.as(new$().object$);
}

extension DeprecatedInterfaceMethods$Methods on DeprecatedInterfaceMethods {
  /// depIos2
  ///
  /// iOS: introduced 1.0.0, deprecated 2.0.0
  int depIos2() {
    objc.checkOsVersionInternal(
      'DeprecatedInterfaceMethods.depIos2',
      iOS: (false, (1, 0, 0)),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_depIos2);
  }

  /// depIos3
  ///
  /// iOS: introduced 1.0.0, deprecated 3.0.0
  int depIos3() {
    objc.checkOsVersionInternal(
      'DeprecatedInterfaceMethods.depIos3',
      iOS: (false, (1, 0, 0)),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_depIos3);
  }

  /// depMac2
  ///
  /// macOS: introduced 1.0.0, deprecated 2.0.0
  int depMac2() {
    objc.checkOsVersionInternal(
      'DeprecatedInterfaceMethods.depMac2',
      macOS: (false, (1, 0, 0)),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_depMac2);
  }

  /// depMac3
  ///
  /// macOS: introduced 1.0.0, deprecated 3.0.0
  int depMac3() {
    objc.checkOsVersionInternal(
      'DeprecatedInterfaceMethods.depMac3',
      macOS: (false, (1, 0, 0)),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_depMac3);
  }

  /// normalMethod
  int normalMethod() {
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_normalMethod);
  }

  /// normalProperty
  int get normalProperty {
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_normalProperty);
  }

  /// setNormalProperty:
  set normalProperty(int value) {
    _objc_msgSend_9o8504(object$.ref.pointer, _sel_setNormalProperty_, value);
  }

  /// unavailableIos
  ///
  /// iOS: unavailable
  int unavailableIos() {
    objc.checkOsVersionInternal(
      'DeprecatedInterfaceMethods.unavailableIos',
      iOS: (true, null),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_unavailableIos);
  }

  /// unavailableMac
  ///
  /// macOS: unavailable
  int unavailableMac() {
    objc.checkOsVersionInternal(
      'DeprecatedInterfaceMethods.unavailableMac',
      macOS: (true, null),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_unavailableMac);
  }
}

/// DeprecatedProtocolMethods
extension type DeprecatedProtocolMethods._(objc.ObjCProtocol object$)
    implements objc.ObjCProtocol, objc.NSObjectProtocol {
  /// Constructs a [DeprecatedProtocolMethods] that points to the same underlying object as [other].
  DeprecatedProtocolMethods.as(objc.ObjCObject other) : object$ = other;

  /// Constructs a [DeprecatedProtocolMethods] that wraps the given raw object pointer.
  DeprecatedProtocolMethods.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCProtocol(other, retain: retain, release: release);

  /// Returns whether [obj] is an instance of [DeprecatedProtocolMethods].
  static bool conformsTo(objc.ObjCObject obj) {
    return _objc_msgSend_e3qsqz(
      obj.ref.pointer,
      _sel_conformsToProtocol_,
      _protocol_DeprecatedProtocolMethods,
    );
  }
}

extension DeprecatedProtocolMethods$Methods on DeprecatedProtocolMethods {
  /// protDepIos2
  ///
  /// iOS: introduced 1.0.0, deprecated 2.0.0
  int protDepIos2() {
    objc.checkOsVersionInternal(
      'DeprecatedProtocolMethods.protDepIos2',
      iOS: (false, (1, 0, 0)),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_protDepIos2);
  }

  /// protDepIos3
  ///
  /// iOS: introduced 1.0.0, deprecated 3.0.0
  int protDepIos3() {
    objc.checkOsVersionInternal(
      'DeprecatedProtocolMethods.protDepIos3',
      iOS: (false, (1, 0, 0)),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_protDepIos3);
  }

  /// protDepMac2
  ///
  /// macOS: introduced 1.0.0, deprecated 2.0.0
  int protDepMac2() {
    objc.checkOsVersionInternal(
      'DeprecatedProtocolMethods.protDepMac2',
      macOS: (false, (1, 0, 0)),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_protDepMac2);
  }

  /// protDepMac3
  ///
  /// macOS: introduced 1.0.0, deprecated 3.0.0
  int protDepMac3() {
    objc.checkOsVersionInternal(
      'DeprecatedProtocolMethods.protDepMac3',
      macOS: (false, (1, 0, 0)),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_protDepMac3);
  }

  /// protNormalMethod
  int protNormalMethod() {
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_protNormalMethod);
  }

  /// protNormalProperty
  int get protNormalProperty {
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_protNormalProperty);
  }

  /// protUnavailableIos
  ///
  /// iOS: unavailable
  int protUnavailableIos() {
    objc.checkOsVersionInternal(
      'DeprecatedProtocolMethods.protUnavailableIos',
      iOS: (true, null),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_protUnavailableIos);
  }

  /// protUnavailableMac
  ///
  /// macOS: unavailable
  int protUnavailableMac() {
    objc.checkOsVersionInternal(
      'DeprecatedProtocolMethods.protUnavailableMac',
      macOS: (true, null),
    );
    return _objc_msgSend_13yqbb6(object$.ref.pointer, _sel_protUnavailableMac);
  }

  /// setProtNormalProperty:
  set protNormalProperty(int value) {
    _objc_msgSend_9o8504(
      object$.ref.pointer,
      _sel_setProtNormalProperty_,
      value,
    );
  }
}

interface class DeprecatedProtocolMethods$Builder {
  /// Returns the [objc.Protocol] object for this protocol.
  static objc.Protocol get $protocol =>
      objc.Protocol.fromPointer(_protocol_DeprecatedProtocolMethods.cast());

  /// Builds an object that implements the DeprecatedProtocolMethods protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly.
  ///
  /// If `$keepIsolateAlive` is true, this protocol will keep this isolate
  /// alive until it is garbage collected by both Dart and ObjC.
  static DeprecatedProtocolMethods implement({
    required int Function() protDepIos2,
    required int Function() protDepIos3,
    required int Function() protDepMac2,
    required int Function() protDepMac3,
    required int Function() protNormalMethod,
    required int Function() protNormalProperty,
    required int Function() protUnavailableIos,
    required int Function() protUnavailableMac,
    required void Function(int) setProtNormalProperty_,
    bool $keepIsolateAlive = true,
  }) {
    final builder = objc.ObjCProtocolBuilder(
      debugName: 'DeprecatedProtocolMethods',
    );
    DeprecatedProtocolMethods$Builder.protDepIos2.implement(
      builder,
      protDepIos2,
    );
    DeprecatedProtocolMethods$Builder.protDepIos3.implement(
      builder,
      protDepIos3,
    );
    DeprecatedProtocolMethods$Builder.protDepMac2.implement(
      builder,
      protDepMac2,
    );
    DeprecatedProtocolMethods$Builder.protDepMac3.implement(
      builder,
      protDepMac3,
    );
    DeprecatedProtocolMethods$Builder.protNormalMethod.implement(
      builder,
      protNormalMethod,
    );
    DeprecatedProtocolMethods$Builder.protNormalProperty.implement(
      builder,
      protNormalProperty,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableIos.implement(
      builder,
      protUnavailableIos,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableMac.implement(
      builder,
      protUnavailableMac,
    );
    DeprecatedProtocolMethods$Builder.setProtNormalProperty_.implement(
      builder,
      setProtNormalProperty_,
    );
    builder.addProtocol($protocol);
    return DeprecatedProtocolMethods.as(
      builder.build(keepIsolateAlive: $keepIsolateAlive),
    );
  }

  /// Adds the implementation of the DeprecatedProtocolMethods protocol to an existing
  /// [objc.ObjCProtocolBuilder].
  ///
  /// Note: You cannot call this method after you have called `builder.build`.
  static void addToBuilder(
    objc.ObjCProtocolBuilder builder, {
    required int Function() protDepIos2,
    required int Function() protDepIos3,
    required int Function() protDepMac2,
    required int Function() protDepMac3,
    required int Function() protNormalMethod,
    required int Function() protNormalProperty,
    required int Function() protUnavailableIos,
    required int Function() protUnavailableMac,
    required void Function(int) setProtNormalProperty_,
    bool $keepIsolateAlive = true,
  }) {
    DeprecatedProtocolMethods$Builder.protDepIos2.implement(
      builder,
      protDepIos2,
    );
    DeprecatedProtocolMethods$Builder.protDepIos3.implement(
      builder,
      protDepIos3,
    );
    DeprecatedProtocolMethods$Builder.protDepMac2.implement(
      builder,
      protDepMac2,
    );
    DeprecatedProtocolMethods$Builder.protDepMac3.implement(
      builder,
      protDepMac3,
    );
    DeprecatedProtocolMethods$Builder.protNormalMethod.implement(
      builder,
      protNormalMethod,
    );
    DeprecatedProtocolMethods$Builder.protNormalProperty.implement(
      builder,
      protNormalProperty,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableIos.implement(
      builder,
      protUnavailableIos,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableMac.implement(
      builder,
      protUnavailableMac,
    );
    DeprecatedProtocolMethods$Builder.setProtNormalProperty_.implement(
      builder,
      setProtNormalProperty_,
    );
    builder.addProtocol($protocol);
  }

  /// Builds an object that implements the DeprecatedProtocolMethods protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly. All
  /// methods that can be implemented as listeners will be.
  ///
  /// If `$keepIsolateAlive` is true, this protocol will keep this isolate
  /// alive until it is garbage collected by both Dart and ObjC.
  static DeprecatedProtocolMethods implementAsListener({
    required int Function() protDepIos2,
    required int Function() protDepIos3,
    required int Function() protDepMac2,
    required int Function() protDepMac3,
    required int Function() protNormalMethod,
    required int Function() protNormalProperty,
    required int Function() protUnavailableIos,
    required int Function() protUnavailableMac,
    required void Function(int) setProtNormalProperty_,
    bool $keepIsolateAlive = true,
  }) {
    final builder = objc.ObjCProtocolBuilder(
      debugName: 'DeprecatedProtocolMethods',
    );
    DeprecatedProtocolMethods$Builder.protDepIos2.implement(
      builder,
      protDepIos2,
    );
    DeprecatedProtocolMethods$Builder.protDepIos3.implement(
      builder,
      protDepIos3,
    );
    DeprecatedProtocolMethods$Builder.protDepMac2.implement(
      builder,
      protDepMac2,
    );
    DeprecatedProtocolMethods$Builder.protDepMac3.implement(
      builder,
      protDepMac3,
    );
    DeprecatedProtocolMethods$Builder.protNormalMethod.implement(
      builder,
      protNormalMethod,
    );
    DeprecatedProtocolMethods$Builder.protNormalProperty.implement(
      builder,
      protNormalProperty,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableIos.implement(
      builder,
      protUnavailableIos,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableMac.implement(
      builder,
      protUnavailableMac,
    );
    DeprecatedProtocolMethods$Builder.setProtNormalProperty_
        .implementAsListener(builder, setProtNormalProperty_);
    builder.addProtocol($protocol);
    return DeprecatedProtocolMethods.as(
      builder.build(keepIsolateAlive: $keepIsolateAlive),
    );
  }

  /// Adds the implementation of the DeprecatedProtocolMethods protocol to an existing
  /// [objc.ObjCProtocolBuilder]. All methods that can be implemented as listeners will
  /// be.
  ///
  /// Note: You cannot call this method after you have called `builder.build`.
  static void addToBuilderAsListener(
    objc.ObjCProtocolBuilder builder, {
    required int Function() protDepIos2,
    required int Function() protDepIos3,
    required int Function() protDepMac2,
    required int Function() protDepMac3,
    required int Function() protNormalMethod,
    required int Function() protNormalProperty,
    required int Function() protUnavailableIos,
    required int Function() protUnavailableMac,
    required void Function(int) setProtNormalProperty_,
    bool $keepIsolateAlive = true,
  }) {
    DeprecatedProtocolMethods$Builder.protDepIos2.implement(
      builder,
      protDepIos2,
    );
    DeprecatedProtocolMethods$Builder.protDepIos3.implement(
      builder,
      protDepIos3,
    );
    DeprecatedProtocolMethods$Builder.protDepMac2.implement(
      builder,
      protDepMac2,
    );
    DeprecatedProtocolMethods$Builder.protDepMac3.implement(
      builder,
      protDepMac3,
    );
    DeprecatedProtocolMethods$Builder.protNormalMethod.implement(
      builder,
      protNormalMethod,
    );
    DeprecatedProtocolMethods$Builder.protNormalProperty.implement(
      builder,
      protNormalProperty,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableIos.implement(
      builder,
      protUnavailableIos,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableMac.implement(
      builder,
      protUnavailableMac,
    );
    DeprecatedProtocolMethods$Builder.setProtNormalProperty_
        .implementAsListener(builder, setProtNormalProperty_);
    builder.addProtocol($protocol);
  }

  /// Builds an object that implements the DeprecatedProtocolMethods protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly. All
  /// methods that can be implemented as blocking listeners will be.
  ///
  /// If `$keepIsolateAlive` is true, this protocol will keep this isolate
  /// alive until it is garbage collected by both Dart and ObjC.
  static DeprecatedProtocolMethods implementAsBlocking({
    required int Function() protDepIos2,
    required int Function() protDepIos3,
    required int Function() protDepMac2,
    required int Function() protDepMac3,
    required int Function() protNormalMethod,
    required int Function() protNormalProperty,
    required int Function() protUnavailableIos,
    required int Function() protUnavailableMac,
    required void Function(int) setProtNormalProperty_,
    bool $keepIsolateAlive = true,
  }) {
    final builder = objc.ObjCProtocolBuilder(
      debugName: 'DeprecatedProtocolMethods',
    );
    DeprecatedProtocolMethods$Builder.protDepIos2.implement(
      builder,
      protDepIos2,
    );
    DeprecatedProtocolMethods$Builder.protDepIos3.implement(
      builder,
      protDepIos3,
    );
    DeprecatedProtocolMethods$Builder.protDepMac2.implement(
      builder,
      protDepMac2,
    );
    DeprecatedProtocolMethods$Builder.protDepMac3.implement(
      builder,
      protDepMac3,
    );
    DeprecatedProtocolMethods$Builder.protNormalMethod.implement(
      builder,
      protNormalMethod,
    );
    DeprecatedProtocolMethods$Builder.protNormalProperty.implement(
      builder,
      protNormalProperty,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableIos.implement(
      builder,
      protUnavailableIos,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableMac.implement(
      builder,
      protUnavailableMac,
    );
    DeprecatedProtocolMethods$Builder.setProtNormalProperty_
        .implementAsBlocking(builder, setProtNormalProperty_);
    builder.addProtocol($protocol);
    return DeprecatedProtocolMethods.as(
      builder.build(keepIsolateAlive: $keepIsolateAlive),
    );
  }

  /// Adds the implementation of the DeprecatedProtocolMethods protocol to an existing
  /// [objc.ObjCProtocolBuilder]. All methods that can be implemented as blocking
  /// listeners will be.
  ///
  /// Note: You cannot call this method after you have called `builder.build`.
  static void addToBuilderAsBlocking(
    objc.ObjCProtocolBuilder builder, {
    required int Function() protDepIos2,
    required int Function() protDepIos3,
    required int Function() protDepMac2,
    required int Function() protDepMac3,
    required int Function() protNormalMethod,
    required int Function() protNormalProperty,
    required int Function() protUnavailableIos,
    required int Function() protUnavailableMac,
    required void Function(int) setProtNormalProperty_,
    bool $keepIsolateAlive = true,
  }) {
    DeprecatedProtocolMethods$Builder.protDepIos2.implement(
      builder,
      protDepIos2,
    );
    DeprecatedProtocolMethods$Builder.protDepIos3.implement(
      builder,
      protDepIos3,
    );
    DeprecatedProtocolMethods$Builder.protDepMac2.implement(
      builder,
      protDepMac2,
    );
    DeprecatedProtocolMethods$Builder.protDepMac3.implement(
      builder,
      protDepMac3,
    );
    DeprecatedProtocolMethods$Builder.protNormalMethod.implement(
      builder,
      protNormalMethod,
    );
    DeprecatedProtocolMethods$Builder.protNormalProperty.implement(
      builder,
      protNormalProperty,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableIos.implement(
      builder,
      protUnavailableIos,
    );
    DeprecatedProtocolMethods$Builder.protUnavailableMac.implement(
      builder,
      protUnavailableMac,
    );
    DeprecatedProtocolMethods$Builder.setProtNormalProperty_
        .implementAsBlocking(builder, setProtNormalProperty_);
    builder.addProtocol($protocol);
  }

  /// protDepIos2
  ///
  /// iOS: introduced 1.0.0, deprecated 2.0.0
  static final protDepIos2 = objc.ObjCProtocolMethod<int Function()>(
    _protocol_DeprecatedProtocolMethods,
    _sel_protDepIos2,
    ffi.Native.addressOf<
          ffi.NativeFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >
        >(_1flqfr_protocolTrampoline_1l0nlq)
        .cast(),
    objc.getProtocolMethodSignature(
      _protocol_DeprecatedProtocolMethods,
      _sel_protDepIos2,
      isRequired: true,
      isInstanceMethod: true,
    ),
    (int Function() func) => ObjCBlock_ffiInt_ffiVoid.fromFunction(
      (ffi.Pointer<ffi.Void> _) => func(),
    ),
  );

  /// protDepIos3
  ///
  /// iOS: introduced 1.0.0, deprecated 3.0.0
  static final protDepIos3 = objc.ObjCProtocolMethod<int Function()>(
    _protocol_DeprecatedProtocolMethods,
    _sel_protDepIos3,
    ffi.Native.addressOf<
          ffi.NativeFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >
        >(_1flqfr_protocolTrampoline_1l0nlq)
        .cast(),
    objc.getProtocolMethodSignature(
      _protocol_DeprecatedProtocolMethods,
      _sel_protDepIos3,
      isRequired: true,
      isInstanceMethod: true,
    ),
    (int Function() func) => ObjCBlock_ffiInt_ffiVoid.fromFunction(
      (ffi.Pointer<ffi.Void> _) => func(),
    ),
  );

  /// protDepMac2
  ///
  /// macOS: introduced 1.0.0, deprecated 2.0.0
  static final protDepMac2 = objc.ObjCProtocolMethod<int Function()>(
    _protocol_DeprecatedProtocolMethods,
    _sel_protDepMac2,
    ffi.Native.addressOf<
          ffi.NativeFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >
        >(_1flqfr_protocolTrampoline_1l0nlq)
        .cast(),
    objc.getProtocolMethodSignature(
      _protocol_DeprecatedProtocolMethods,
      _sel_protDepMac2,
      isRequired: true,
      isInstanceMethod: true,
    ),
    (int Function() func) => ObjCBlock_ffiInt_ffiVoid.fromFunction(
      (ffi.Pointer<ffi.Void> _) => func(),
    ),
  );

  /// protDepMac3
  ///
  /// macOS: introduced 1.0.0, deprecated 3.0.0
  static final protDepMac3 = objc.ObjCProtocolMethod<int Function()>(
    _protocol_DeprecatedProtocolMethods,
    _sel_protDepMac3,
    ffi.Native.addressOf<
          ffi.NativeFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >
        >(_1flqfr_protocolTrampoline_1l0nlq)
        .cast(),
    objc.getProtocolMethodSignature(
      _protocol_DeprecatedProtocolMethods,
      _sel_protDepMac3,
      isRequired: true,
      isInstanceMethod: true,
    ),
    (int Function() func) => ObjCBlock_ffiInt_ffiVoid.fromFunction(
      (ffi.Pointer<ffi.Void> _) => func(),
    ),
  );

  /// protNormalMethod
  static final protNormalMethod = objc.ObjCProtocolMethod<int Function()>(
    _protocol_DeprecatedProtocolMethods,
    _sel_protNormalMethod,
    ffi.Native.addressOf<
          ffi.NativeFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >
        >(_1flqfr_protocolTrampoline_1l0nlq)
        .cast(),
    objc.getProtocolMethodSignature(
      _protocol_DeprecatedProtocolMethods,
      _sel_protNormalMethod,
      isRequired: true,
      isInstanceMethod: true,
    ),
    (int Function() func) => ObjCBlock_ffiInt_ffiVoid.fromFunction(
      (ffi.Pointer<ffi.Void> _) => func(),
    ),
  );

  /// protNormalProperty
  static final protNormalProperty = objc.ObjCProtocolMethod<int Function()>(
    _protocol_DeprecatedProtocolMethods,
    _sel_protNormalProperty,
    ffi.Native.addressOf<
          ffi.NativeFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >
        >(_1flqfr_protocolTrampoline_1l0nlq)
        .cast(),
    objc.getProtocolMethodSignature(
      _protocol_DeprecatedProtocolMethods,
      _sel_protNormalProperty,
      isRequired: true,
      isInstanceMethod: true,
    ),
    (int Function() func) => ObjCBlock_ffiInt_ffiVoid.fromFunction(
      (ffi.Pointer<ffi.Void> _) => func(),
    ),
  );

  /// protUnavailableIos
  ///
  /// iOS: unavailable
  static final protUnavailableIos = objc.ObjCProtocolMethod<int Function()>(
    _protocol_DeprecatedProtocolMethods,
    _sel_protUnavailableIos,
    ffi.Native.addressOf<
          ffi.NativeFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >
        >(_1flqfr_protocolTrampoline_1l0nlq)
        .cast(),
    objc.getProtocolMethodSignature(
      _protocol_DeprecatedProtocolMethods,
      _sel_protUnavailableIos,
      isRequired: true,
      isInstanceMethod: true,
    ),
    (int Function() func) => ObjCBlock_ffiInt_ffiVoid.fromFunction(
      (ffi.Pointer<ffi.Void> _) => func(),
    ),
  );

  /// protUnavailableMac
  ///
  /// macOS: unavailable
  static final protUnavailableMac = objc.ObjCProtocolMethod<int Function()>(
    _protocol_DeprecatedProtocolMethods,
    _sel_protUnavailableMac,
    ffi.Native.addressOf<
          ffi.NativeFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >
        >(_1flqfr_protocolTrampoline_1l0nlq)
        .cast(),
    objc.getProtocolMethodSignature(
      _protocol_DeprecatedProtocolMethods,
      _sel_protUnavailableMac,
      isRequired: true,
      isInstanceMethod: true,
    ),
    (int Function() func) => ObjCBlock_ffiInt_ffiVoid.fromFunction(
      (ffi.Pointer<ffi.Void> _) => func(),
    ),
  );

  /// setProtNormalProperty:
  static final setProtNormalProperty_ =
      objc.ObjCProtocolListenableMethod<void Function(int)>(
        _protocol_DeprecatedProtocolMethods,
        _sel_setProtNormalProperty_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Void Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Int,
                )
              >
            >(_1flqfr_protocolTrampoline_1t7vjnw)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_DeprecatedProtocolMethods,
          _sel_setProtNormalProperty_,
          isRequired: true,
          isInstanceMethod: true,
        ),
        (void Function(int) func) =>
            ObjCBlock_ffiVoid_ffiVoid_ffiInt.fromFunction(
              (ffi.Pointer<ffi.Void> _, int arg1) => func(arg1),
            ),
        (void Function(int) func) => ObjCBlock_ffiVoid_ffiVoid_ffiInt.listener(
          (ffi.Pointer<ffi.Void> _, int arg1) => func(arg1),
        ),
        (void Function(int) func) => ObjCBlock_ffiVoid_ffiVoid_ffiInt.blocking(
          (ffi.Pointer<ffi.Void> _, int arg1) => func(arg1),
        ),
      );
}

enum NormalEnum {
  x(0);

  final int value;
  const NormalEnum(this.value);

  static NormalEnum fromValue(int value) => switch (value) {
    0 => x,
    _ => throw ArgumentError('Unknown value for NormalEnum: $value'),
  };
}

final class NormalStruct extends ffi.Struct {
  @ffi.Int()
  external int x;
}

final class NormalUnion extends ffi.Union {
  @ffi.Int()
  external int x;
}

/// Construction methods for `objc.ObjCBlock<ffi.Int Function(ffi.Pointer<ffi.Void>)>`.
abstract final class ObjCBlock_ffiInt_ffiVoid {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.Int Function(ffi.Pointer<ffi.Void>)> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.Int Function(ffi.Pointer<ffi.Void>)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.Int Function(ffi.Pointer<ffi.Void>)>
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void> arg0)>
    >
    ptr,
  ) => objc.ObjCBlock<ffi.Int Function(ffi.Pointer<ffi.Void>)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Int Function(ffi.Pointer<ffi.Void>)> fromFunction(
    int Function(ffi.Pointer<ffi.Void>) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.Int Function(ffi.Pointer<ffi.Void>)>(
    objc.newClosureBlock(
      _closureCallable,
      (ffi.Pointer<ffi.Void> arg0) => fn(arg0),
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  static int _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
  ) => block.ref.target
      .cast<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void> arg0)>>()
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >(_fnPtrTrampoline, 0)
          .cast();
  static int _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
  ) => (objc.getBlockClosure(block) as int Function(ffi.Pointer<ffi.Void>))(
    arg0,
  );
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Int Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >(_closureTrampoline, 0)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Int Function(ffi.Pointer<ffi.Void>)>`.
extension ObjCBlock_ffiInt_ffiVoid$CallExtension
    on objc.ObjCBlock<ffi.Int Function(ffi.Pointer<ffi.Void>)> {
  int call(ffi.Pointer<ffi.Void> arg0) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<ffi.Void> arg0,
          )
        >
      >()
      .asFunction<
        int Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Pointer<ffi.Void>)
      >()(ref.pointer, arg0);
}

/// Construction methods for `objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>`.
abstract final class ObjCBlock_ffiVoid_ffiVoid_ffiInt {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<ffi.Void> arg0, ffi.Int arg1)
      >
    >
    ptr,
  ) => objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>
  fromFunction(
    void Function(ffi.Pointer<ffi.Void>, int) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>(
    objc.newClosureBlock(
      _closureCallable,
      (ffi.Pointer<ffi.Void> arg0, int arg1) => fn(arg0, arg1),
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  /// Creates a listener block from a Dart function.
  ///
  /// This is based on FFI's NativeCallable.listener, and has the same
  /// capabilities and limitations. This block can be invoked from any thread,
  /// but only supports void functions, and is not run synchronously. See
  /// NativeCallable.listener for more details.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>
  listener(
    void Function(ffi.Pointer<ffi.Void>, int) fn, {
    bool keepIsolateAlive = true,
  }) {
    final raw = objc.newClosureBlock(
      _listenerCallable.nativeFunction.cast(),
      (ffi.Pointer<ffi.Void> arg0, int arg1) => fn(arg0, arg1),
      keepIsolateAlive,
    );
    final wrapper = _1flqfr_wrapListenerBlock_1t7vjnw(raw);
    objc.objectRelease(raw.cast());
    return objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>(
      wrapper,
      retain: false,
      release: true,
    );
  }

  /// Creates a blocking block from a Dart function.
  ///
  /// This callback can be invoked from any native thread, and will block the
  /// caller until the callback is handled by the Dart isolate that created
  /// the block. Async functions are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC. If the owner isolate
  /// has shut down, and the block is invoked by native code, it may block
  /// indefinitely, or have other undefined behavior.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>
  blocking(
    void Function(ffi.Pointer<ffi.Void>, int) fn, {
    bool keepIsolateAlive = true,
  }) {
    final raw = objc.newClosureBlock(
      _blockingCallable.nativeFunction.cast(),
      (ffi.Pointer<ffi.Void> arg0, int arg1) => fn(arg0, arg1),
      keepIsolateAlive,
    );
    final rawListener = objc.newClosureBlock(
      _blockingListenerCallable.nativeFunction.cast(),
      (ffi.Pointer<ffi.Void> arg0, int arg1) => fn(arg0, arg1),
      keepIsolateAlive,
    );
    final wrapper = _1flqfr_wrapBlockingBlock_1t7vjnw(
      raw,
      rawListener,
      objc.objCContext,
    );
    objc.objectRelease(raw.cast());
    objc.objectRelease(rawListener.cast());
    return objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>(
      wrapper,
      retain: false,
      release: true,
    );
  }

  static void _listenerTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    int arg1,
  ) {
    (objc.getBlockClosure(block) as void Function(ffi.Pointer<ffi.Void>, int))(
      arg0,
      arg1,
    );
    objc.objectRelease(block.cast());
  }

  static ffi.NativeCallable<
    ffi.Void Function(
      ffi.Pointer<objc.ObjCBlockImpl>,
      ffi.Pointer<ffi.Void>,
      ffi.Int,
    )
  >
  _listenerCallable =
      ffi.NativeCallable<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
          )
        >.listener(_listenerTrampoline)
        ..keepIsolateAlive = false;
  static void _blockingTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> waiter,
    ffi.Pointer<ffi.Void> arg0,
    int arg1,
  ) {
    try {
      (objc.getBlockClosure(block)
          as void Function(ffi.Pointer<ffi.Void>, int))(arg0, arg1);
    } catch (e) {
    } finally {
      objc.signalWaiter(waiter);
      objc.objectRelease(block.cast());
    }
  }

  static ffi.NativeCallable<
    ffi.Void Function(
      ffi.Pointer<objc.ObjCBlockImpl>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Int,
    )
  >
  _blockingCallable =
      ffi.NativeCallable<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
          )
        >.isolateLocal(_blockingTrampoline)
        ..keepIsolateAlive = false;
  static ffi.NativeCallable<
    ffi.Void Function(
      ffi.Pointer<objc.ObjCBlockImpl>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Void>,
      ffi.Int,
    )
  >
  _blockingListenerCallable =
      ffi.NativeCallable<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
          )
        >.listener(_blockingTrampoline)
        ..keepIsolateAlive = false;
  static void _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    int arg1,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> arg0, ffi.Int arg1)
        >
      >()
      .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>()(arg0, arg1);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Int,
            )
          >(_fnPtrTrampoline)
          .cast();
  static void _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    int arg1,
  ) =>
      (objc.getBlockClosure(block)
          as void Function(ffi.Pointer<ffi.Void>, int))(arg0, arg1);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Int,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>`.
extension ObjCBlock_ffiVoid_ffiVoid_ffiInt$CallExtension
    on objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)> {
  void call(ffi.Pointer<ffi.Void> arg0, int arg1) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<ffi.Void> arg0,
            ffi.Int arg1,
          )
        >
      >()
      .asFunction<
        void Function(
          ffi.Pointer<objc.ObjCBlockImpl>,
          ffi.Pointer<ffi.Void>,
          int,
        )
      >()(ref.pointer, arg0, arg1);
}

late final _class_DeprecatedInterfaceMethods = objc.getClass(
  "DeprecatedInterfaceMethods",
);
final _objc_msgSend_13yqbb6 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Int Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
final _objc_msgSend_9o8504 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Int,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_e3qsqz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCProtocolImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCProtocolImpl>,
      )
    >();
late final _protocol_DeprecatedProtocolMethods = objc.getProtocol(
  "DeprecatedProtocolMethods",
);
late final _sel_alloc = objc.registerName("alloc");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
late final _sel_conformsToProtocol_ = objc.registerName("conformsToProtocol:");
late final _sel_depIos2 = objc.registerName("depIos2");
late final _sel_depIos3 = objc.registerName("depIos3");
late final _sel_depMac2 = objc.registerName("depMac2");
late final _sel_depMac3 = objc.registerName("depMac3");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
late final _sel_new = objc.registerName("new");
late final _sel_normalMethod = objc.registerName("normalMethod");
late final _sel_normalProperty = objc.registerName("normalProperty");
late final _sel_protDepIos2 = objc.registerName("protDepIos2");
late final _sel_protDepIos3 = objc.registerName("protDepIos3");
late final _sel_protDepMac2 = objc.registerName("protDepMac2");
late final _sel_protDepMac3 = objc.registerName("protDepMac3");
late final _sel_protNormalMethod = objc.registerName("protNormalMethod");
late final _sel_protNormalProperty = objc.registerName("protNormalProperty");
late final _sel_protUnavailableIos = objc.registerName("protUnavailableIos");
late final _sel_protUnavailableMac = objc.registerName("protUnavailableMac");
late final _sel_setNormalProperty_ = objc.registerName("setNormalProperty:");
late final _sel_setProtNormalProperty_ = objc.registerName(
  "setProtNormalProperty:",
);
late final _sel_unavailableIos = objc.registerName("unavailableIos");
late final _sel_unavailableMac = objc.registerName("unavailableMac");
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;

const int normalUnnamedEnum = 0;
