// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:ffigen/objc_test')
library;

import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

const _$objcVersionCheck = objc.ObjCVersionCheck(9, 5);
typedef CFAllocatorAllocateCallBackFunction =
    ffi.Pointer<ffi.Void> Function(
      ffi.Long allocSize,
      ffi.UnsignedLong hint,
      ffi.Pointer<ffi.Void> info,
    );
typedef DartCFAllocatorAllocateCallBackFunction =
    ffi.Pointer<ffi.Void> Function(
      int allocSize,
      int hint,
      ffi.Pointer<ffi.Void> info,
    );
typedef CFAllocatorCopyDescriptionCallBackFunction =
    ffi.Pointer<objc.CFString> Function(ffi.Pointer<ffi.Void> info);
typedef CFAllocatorDeallocateCallBackFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> ptr, ffi.Pointer<ffi.Void> info);
typedef DartCFAllocatorDeallocateCallBackFunction =
    void Function(ffi.Pointer<ffi.Void> ptr, ffi.Pointer<ffi.Void> info);
typedef CFAllocatorPreferredSizeCallBackFunction =
    ffi.Long Function(
      ffi.Long size,
      ffi.UnsignedLong hint,
      ffi.Pointer<ffi.Void> info,
    );
typedef DartCFAllocatorPreferredSizeCallBackFunction =
    int Function(int size, int hint, ffi.Pointer<ffi.Void> info);
typedef CFAllocatorReallocateCallBackFunction =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<ffi.Void> ptr,
      ffi.Long newsize,
      ffi.UnsignedLong hint,
      ffi.Pointer<ffi.Void> info,
    );
typedef DartCFAllocatorReallocateCallBackFunction =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<ffi.Void> ptr,
      int newsize,
      int hint,
      ffi.Pointer<ffi.Void> info,
    );
typedef CFAllocatorReleaseCallBackFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> info);
typedef DartCFAllocatorReleaseCallBackFunction =
    void Function(ffi.Pointer<ffi.Void> info);
typedef CFAllocatorRetainCallBackFunction =
    ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void> info);
typedef CFComparatorFunctionFunction =
    ffi.Long Function(
      ffi.Pointer<ffi.Void> val1,
      ffi.Pointer<ffi.Void> val2,
      ffi.Pointer<ffi.Void> context,
    );
typedef DartCFComparatorFunctionFunction =
    CFComparisonResult Function(
      ffi.Pointer<ffi.Void> val1,
      ffi.Pointer<ffi.Void> val2,
      ffi.Pointer<ffi.Void> context,
    );

enum CFComparisonResult {
  kCFCompareLessThan(-1),
  kCFCompareEqualTo(0),
  kCFCompareGreaterThan(1);

  final int value;
  const CFComparisonResult(this.value);

  static CFComparisonResult fromValue(int value) => switch (value) {
    -1 => kCFCompareLessThan,
    0 => kCFCompareEqualTo,
    1 => kCFCompareGreaterThan,
    _ => throw ArgumentError('Unknown value for CFComparisonResult: $value'),
  };
}

typedef IMPFunction = ffi.Void Function();
typedef DartIMPFunction = void Function();
typedef ProcPtrFunction = ffi.Long Function();
typedef DartProcPtrFunction = int Function();
typedef Register68kProcPtrFunction = ffi.Void Function();
typedef DartRegister68kProcPtrFunction = void Function();

/// StringUtil
extension type StringUtil._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [StringUtil] that points to the same underlying object as [other].
  StringUtil.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [StringUtil] that wraps the given raw object pointer.
  StringUtil.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [StringUtil].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_StringUtil,
        );

  /// alloc
  static StringUtil alloc() {
    final $ret = _objc_msgSend_151sglz(_class_StringUtil, _sel_alloc);
    return StringUtil.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static StringUtil allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_StringUtil,
      _sel_allocWithZone_,
      zone,
    );
    return StringUtil.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static StringUtil new$() {
    final $ret = _objc_msgSend_151sglz(_class_StringUtil, _sel_new);
    return StringUtil.fromPointer($ret, retain: false, release: true);
  }

  /// strConcat:with:
  static objc.NSString strConcat(
    objc.NSString a, {
    required objc.NSString with$,
  }) {
    final _$$ref = a.ref;
    final _$$ref$1 = with$.ref;
    final $ret = _objc_msgSend_15qeuct(
      _class_StringUtil,
      _sel_strConcat_with_,
      _$$ref.pointer,
      _$$ref$1.pointer,
    );
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// Returns a new instance of StringUtil constructed with the default `new` method.
  StringUtil() : this.as(new$().object$);
}

extension StringUtil$Methods on StringUtil {
  /// init
  StringUtil init() {
    final _$$ref = object$.ref;
    objc.checkOsVersionInternal(
      'StringUtil.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _$$ref.retainAndReturnPointer(),
      _sel_init,
    );
    return StringUtil.fromPointer($ret, retain: false, release: true);
  }
}

@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$_StringUtil',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class_StringUtil_raw;
final _class_StringUtil = objc.getClass(
  "StringUtil",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_StringUtil_raw,
  ).cast(),
);
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_15qeuct = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
late final _sel_alloc = objc.registerName("alloc");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
late final _sel_init = objc.registerName("init");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
late final _sel_new = objc.registerName("new");
late final _sel_strConcat_with_ = objc.registerName("strConcat:with:");
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
typedef sig_tFunction = ffi.Void Function(ffi.Int);
typedef Dartsig_tFunction = void Function(int);
