// Copyright (c) 2024, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import { createRoot, createSignal } from "solid-js";

export interface LogEntry {
  level: number;
  message: string;
}

/**
 * Array of log entries generated by ffigen
 */
export const $logs = createRoot(() => createSignal<LogEntry[]>([]));
