// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package

const double Box$memberDouble = 2.5;

const int Box$memberInt = 7;

const int Widget$classInt = 99;

const int ns$inner$nsInt = 43;

const int ns$nsInt = 42;

const int scoped$Gadget$gadgetInt = 100;

const int topDerived = 10;

const double topDouble = 3.5;

const int topInt = 5;

const String topStr = 'hello';
