// Copyright (c) 2024, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
import 'dart:io';

import 'package:args/args.dart';
import 'package:yaml/yaml.dart';

import '../../native_assets_cli.dart';
import '../model/link_config.dart';
import '../model/pipeline_config.dart';

/// The input to the linking script.
///
/// It consists of a subset of the fields from the [BuildConfig] already passed
/// to the build script, the [assets] from the build step, and the
/// [resourceIdentifiers] generated during the kernel compilation.
abstract class LinkConfig extends PipelineConfig {
  /// Generate the [LinkConfig] from the input arguments to the linking script.
  static Future<LinkConfig> fromArgs(List<String> args) async {
    final argParser = ArgParser()..addOption('config');

    final results = argParser.parse(args);
    final yaml = loadYaml(File(results['config'] as String).readAsStringSync())
        as YamlMap;

    return LinkConfigArgs.fromYaml(yaml).fromArgs();
  }

  @override
  Uri get configFile;

  @override
  Uri get outDirectory;

  @override
  String get outputName;

  @override
  String get packageName;

  @override
  Uri get packageRoot;

  @override
  Map<String, Object> toYaml();

  /// The URI of the `link.dart` script.
  @override
  Uri get script;

  /// The list of assets to be linked. These are the assets generated by a
  /// `build.dart` script destined for this packages `link.dart`.
  List<Asset> get assets;

  /// A collection of methods annotated with `@ResourceIdentifier`, which are
  /// called in the tree-shaken Dart code. This information can be used to
  /// dispose unused [assets].
  ResourceIdentifiers? get resourceIdentifiers;
}
