// Copyright (c) 2023, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

final class NoPacking extends ffi.Struct {
  @ffi.Uint8()
  external int a;

  static ffi.Pointer<NoPacking> $allocate(
    ffi.Allocator $allocator, {
    required int a,
  }) => $allocator<NoPacking>()..ref.a = a;
}

@ffi.Packed(1)
final class Pack1 extends ffi.Struct {
  @ffi.Uint8()
  external int a;

  static ffi.Pointer<Pack1> $allocate(
    ffi.Allocator $allocator, {
    required int a,
  }) => $allocator<Pack1>()..ref.a = a;
}

@ffi.Packed(16)
final class Pack16 extends ffi.Struct {
  @ffi.Uint8()
  external int a;

  static ffi.Pointer<Pack16> $allocate(
    ffi.Allocator $allocator, {
    required int a,
  }) => $allocator<Pack16>()..ref.a = a;
}

@ffi.Packed(2)
final class Pack2 extends ffi.Struct {
  @ffi.Uint8()
  external int a;

  static ffi.Pointer<Pack2> $allocate(
    ffi.Allocator $allocator, {
    required int a,
  }) => $allocator<Pack2>()..ref.a = a;
}

@ffi.Packed(4)
final class Pack4 extends ffi.Struct {
  @ffi.Uint8()
  external int a;

  static ffi.Pointer<Pack4> $allocate(
    ffi.Allocator $allocator, {
    required int a,
  }) => $allocator<Pack4>()..ref.a = a;
}

@ffi.Packed(8)
final class Pack8 extends ffi.Struct {
  @ffi.Uint8()
  external int a;

  static ffi.Pointer<Pack8> $allocate(
    ffi.Allocator $allocator, {
    required int a,
  }) => $allocator<Pack8>()..ref.a = a;
}
