// Copyright (c) 2023, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

final class CollisionStruct extends ffi.Struct {
  @ffi.Int32()
  external int allocator;

  @ffi.Int32()
  external int allocate;

  static ffi.Pointer<CollisionStruct> allocate$1(
    ffi.Allocator allocator, {
    required int allocatorValue,
    required int allocate,
  }) => allocator<CollisionStruct>()
    ..ref.allocator = allocatorValue
    ..ref.allocate = allocate;
}
