// AUTO GENERATED BY NATIVE_DOC_DARTIFIER. DO NOT EDIT!
// Regenerate this file by running tool/prepare_dartify_test.dart

import '../bindings.dart';

bool identifiersSpecialCases() =>
    Example.has$$dollar$$sign + Example.$_startsWithUnderscore == 3;
