// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

final class A extends ffi.Struct {
  @ffi.Int()
  external int a;

  static ffi.Pointer<A> allocate(ffi.Allocator allocator, {required int a}) =>
      allocator<A>()..ref.a = a;
}

final class B extends ffi.Struct {
  @ffi.Int()
  external int B$1;

  @ffi.Int()
  external int A$1;

  static ffi.Pointer<B> allocate(
    ffi.Allocator allocator, {
    required int B$1,
    required int A$1,
  }) => allocator<B>()
    ..ref.B$1 = B$1
    ..ref.A$1 = A$1;
}

final class C extends ffi.Struct {
  external A A$1;

  external B B$1;
}

final class D extends ffi.Struct {
  external B A$1;

  external A B$1;
}
