name: objective_c_helper
description: Helper utilities for objective_c tests and hooks.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  logging: ^1.3.0
  native_toolchain_c: ^0.17.4

dev_dependencies:
  hooks:
    path: ../hooks

dependency_overrides:
  native_toolchain_c:
    path: ../native_toolchain_c
