name: android_test_runner
description: Android integration tests for jni_flutter
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jni_flutter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

dependency_overrides:
  jni:
    path: ../../jni

flutter:
  uses-material-design: true
