// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';

import 'package:ffigen/ffigen.dart';
import 'package:ffigen/src/config_provider/yaml_config.dart';
import 'package:ffigen/src/header_parser.dart' show parse;
import 'package:ffigen/src/migration.dart' show migrate;
import 'package:package_config/package_config_types.dart';
import 'package:path/path.dart' as path;
import 'package:test/test.dart';
import 'package:yaml/yaml.dart' as yaml;

import '../test_utils.dart';

String findOriginalPath(String fileName, String repoRoot, String ffigenRoot) {
  return path.join(ffigenRoot, 'test', 'migrate', 'yaml', fileName);
}

void compareDirectories(Directory expectedDir, Directory actualDir) {
  if (!expectedDir.existsSync()) {
    fail("Expected bindings directory doesn't exist: ${expectedDir.path}");
  }
  if (!actualDir.existsSync()) {
    fail("Actual bindings directory doesn't exist: ${actualDir.path}");
  }

  final actualFiles = actualDir
      .listSync(recursive: true)
      .whereType<File>()
      .toList();
  if (actualFiles.isEmpty) {
    fail('No bindings generated by Dart script into ${actualDir.path}');
  }

  final diffResult = Process.runSync('git', [
    'diff',
    '--no-index',
    '--color=always',
    expectedDir.path,
    actualDir.path,
  ]);
  if (diffResult.exitCode != 0) {
    fail(
      'Bindings generated from Dart script do not match expected YAML '
      'bindings:\n'
      '${diffResult.stdout}\n'
      '  ${expectedDir.path}\n'
      '      vs\n'
      '  ${actualDir.path}',
    );
  }
}

String _resolveIncludePath(String opt, String configDir) {
  if (!opt.startsWith('-I')) return opt;
  final incPath = opt.substring(2);
  if (!path.isRelative(incPath)) return opt;

  final resolvedFromConfig = path.normalize(path.join(configDir, incPath));
  if (FileSystemEntity.typeSync(resolvedFromConfig) !=
      FileSystemEntityType.notFound) {
    return '-I$resolvedFromConfig';
  }
  final resolvedFromPackage = path.normalize(
    path.join(packagePathForTests, incPath),
  );
  if (FileSystemEntity.typeSync(resolvedFromPackage) !=
      FileSystemEntityType.notFound) {
    return '-I$resolvedFromPackage';
  }
  return opt;
}

Future<void> verifyMigration(
  File yamlFile, {
  bool Function(String expected, String actual)? dartVerify,
  bool Function(String expected, String actual)? objCVerify,
  bool Function(String expected, String actual)? cppVerify,
}) async {
  final testName = path.basenameWithoutExtension(yamlFile.path);
  final repoRoot = path.normalize(path.join(packagePathForTests, '..', '..'));
  final origConfigPath = findOriginalPath(
    path.basename(yamlFile.path),
    repoRoot,
    packagePathForTests,
  );

  final yamlContent = yamlFile.readAsStringSync();
  final yamlMap = yaml.loadYaml(yamlContent) as yaml.YamlMap;
  final logger = createTestLogger();
  final yamlConfig = YamlConfig.fromYaml(
    yamlMap,
    logger,
    filename: origConfigPath,
    packageConfig: PackageConfig([
      Package(
        'shared_bindings',
        Uri.file(
          path.join(packagePathForTests, 'example', 'shared_bindings', 'lib/'),
        ),
      ),
    ]),
  );

  final config = yamlConfig.configAdapter();
  final configDir = path.dirname(origConfigPath);
  final compilerOptions = config.input.compilerOptions;
  if (compilerOptions != null) {
    final newOptions = [
      for (final opt in compilerOptions) _resolveIncludePath(opt, configDir),
    ];
    compilerOptions
      ..clear()
      ..addAll(newOptions);
  }
  final context = testContext(config);
  final library = parse(context);

  // 1. Generate YAML bindings and verify against checked-in copy.
  final bindingsRelativeDir = ['test', 'migrate', 'bindings', testName];
  Directory(
    path.joinAll([packagePathForTests, ...bindingsRelativeDir]),
  ).createSync(recursive: true);

  final dartFileName = path.basename(config.output.dart.path.toFilePath());
  await matchLibraryWithExpected(
    context,
    library,
    path.join('bindings', testName, dartFileName),
    [...bindingsRelativeDir, dartFileName],
    format: config.output.format,
    verify: dartVerify,
    analyze: false,
  );

  final objCFileName = path.basename(config.output.objCFile.toFilePath());
  await matchObjCFileWithExpected(
    context,
    library,
    path.join('bindings', testName, objCFileName),
    [...bindingsRelativeDir, objCFileName],
    verify: objCVerify,
  );

  final cppFileName = path.basename(config.output.cppBindingsFile.toFilePath());
  await matchCppFileWithExpected(
    context,
    library,
    path.join('bindings', testName, cppFileName),
    [...bindingsRelativeDir, cppFileName],
    verify: cppVerify,
  );

  final symbolFile = config.output.symbolFile;
  if (symbolFile != null) {
    final symbolFileName = path.basename(symbolFile.output.toFilePath());
    await matchLibrarySymbolFileWithExpected(
      context,
      library,
      path.join('bindings', testName, symbolFileName),
      [...bindingsRelativeDir, symbolFileName],
      symbolFile.importPath.toString(),
    );
  }

  final recordUseMapping = config.output.recordUseMapping;
  if (recordUseMapping != null) {
    final recordUseFileName = path.basename(recordUseMapping.toFilePath());
    await matchRecordUseMappingWithExpected(
      context,
      library,
      path.join('bindings', testName, recordUseFileName),
      [...bindingsRelativeDir, recordUseFileName],
      format: config.output.format,
    );
  }

  // 2. Run YAML config through migrator and verify Dart script against
  // checked-in.
  final dartScriptRelativePath = ['test', 'migrate', 'dart', '$testName.dart'];
  final expectedDartScriptFile = File(
    path.joinAll([packagePathForTests, ...dartScriptRelativePath]),
  );
  expectedDartScriptFile.parent.createSync(recursive: true);

  await matchFileWithExpected(
    context: context,
    pathForActual: path.join('dart', '$testName.dart'),
    pathToExpected: dartScriptRelativePath,
    fileWriter: (File file, _) =>
        migrate(yamlConfig: yamlFile, outputDart: file),
  );

  // 3. Run the generated Dart script to generate bindings into temp location.
  final scriptToRun = expectedDartScriptFile.existsSync()
      ? expectedDartScriptFile
      : File(path.join(context.tmpDir, 'dart', '$testName.dart'));

  final tmpBase = Directory(
    path.join(packagePathForTests, 'test', 'migrate', '.tmp'),
  );
  final tempDartGenDir = Directory(path.join(tmpBase.path, testName))
    ..createSync(recursive: true);

  try {
    final runResult = await Process.run(
      Platform.resolvedExecutable,
      ['run', scriptToRun.path, tempDartGenDir.path],
      workingDirectory: packagePathForTests,
      environment: {'OUTPUT_DIR': tempDartGenDir.path},
    );
    if (runResult.exitCode != 0) {
      fail(
        'Running Dart script ${scriptToRun.path} failed with exit code '
        '${runResult.exitCode}:\n'
        '${runResult.stderr}\n${runResult.stdout}',
      );
    }

    // 4. Verify bindings from YAML and from Dart script are the same.
    final checkedInBindingsDir = Directory(
      path.joinAll([packagePathForTests, ...bindingsRelativeDir]),
    );
    compareDirectories(checkedInBindingsDir, tempDartGenDir);
  } finally {
    if (tempDartGenDir.existsSync()) {
      tempDartGenDir.deleteSync(recursive: true);
    }
    if (tmpBase.existsSync() && tmpBase.listSync().isEmpty) {
      tmpBase.deleteSync();
    }
  }
}
