name: jni_flutter
description: Flutter-specific APIs for package:jni.
version: 0.1.0-wip
publish_to: 'none'
repository: https://github.com/dart-lang/native/tree/main/pkgs/jni_flutter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.35.6'

dependencies:
  flutter:
    sdk: flutter
  jni:
    path: ../jni

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter
  jnigen:
    path: ../jnigen

flutter:
  plugin:
    platforms:
      android:
        package: com.github.dart_lang.jni
        pluginClass: JniPlugin
