# Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: jni_flutter
description: A library to access Flutter Android specific APIs from Dart.
version: 1.0.1
repository: https://github.com/dart-lang/native/tree/main/pkgs/jni_flutter
issue_tracker: https://github.com/dart-lang/native/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Ajni_flutter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.35.6'

dependencies:
  flutter:
    sdk: flutter
  jni: ^1.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  jnigen:
    path: ../jnigen

dependency_overrides:
  jni:
    path: ../jni

flutter:
  plugin:
    platforms:
      android:
        package: com.github.dart_lang.jni_flutter
        pluginClass: JniFlutterPlugin
