// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:ffigen/native_test')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Bool Function(ffi.Bool)>()
external bool Function1Bool(bool x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double Function1Double(double x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double Function1Float(double x);

@ffi.Native<ffi.Int16 Function(ffi.Int16)>()
external int Function1Int16(int x);

@ffi.Native<ffi.Int32 Function(ffi.Int32)>()
external int Function1Int32(int x);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int Function1Int64(int x);

@ffi.Native<ffi.Int8 Function(ffi.Int8)>()
external int Function1Int8(int x);

@ffi.Native<ffi.IntPtr Function(ffi.IntPtr)>()
external int Function1IntPtr(int x);

@ffi.Native<ffi.Int Function(Struct3)>()
external int Function1StructPassByValue(Struct3 sum_a_b_c);

@ffi.Native<Struct3 Function(ffi.Int, ffi.Int, ffi.Int)>()
external Struct3 Function1StructReturnByValue(int a, int b, int c);

@ffi.Native<ffi.Uint16 Function(ffi.Uint16)>()
external int Function1Uint16(int x);

@ffi.Native<ffi.Uint32 Function(ffi.Uint32)>()
external int Function1Uint32(int x);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int Function1Uint64(int x);

@ffi.Native<ffi.Uint8 Function(ffi.Uint8)>()
external int Function1Uint8(int x);

@ffi.Native<ffi.UintPtr Function(ffi.UintPtr)>()
external int Function1UintPtr(int x);

@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt)>(symbol: 'funcWithEnum1')
external int _funcWithEnum1(int value);

Enum1 funcWithEnum1(Enum1 value) =>
    Enum1.fromValue(_funcWithEnum1(value.value));

@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt)>()
external int funcWithEnum2(int value);

@ffi.Native<ffi.Pointer<Struct1> Function()>()
external ffi.Pointer<Struct1> getStruct1();

@ffi.Native<StructWithEnums Function()>()
external StructWithEnums getStructWithEnums();

@ffi.Array.multi([3])
@ffi.Native<ffi.Array<ffi.Int>>()
external ffi.Array<ffi.Int> globalArray;

enum Enum1 {
  enum1Value1(0),
  enum1Value2(1),
  enum1Value3(2);

  final int value;
  const Enum1(this.value);

  static Enum1 fromValue(int value) => switch (value) {
    0 => enum1Value1,
    1 => enum1Value2,
    2 => enum1Value3,
    _ => throw ArgumentError('Unknown value for Enum1: $value'),
  };
}

sealed class Enum2 {
  static const enum2Value1 = 0;
  static const enum2Value2 = 1;
  static const enum2Value3 = 2;
}

final class Struct1 extends ffi.Struct {
  @ffi.Int8()
  external int a;

  @ffi.Array.multi([3, 1, 2])
  external ffi.Array<ffi.Array<ffi.Array<ffi.Int32>>> data;
}

final class Struct3 extends ffi.Struct {
  @ffi.Int()
  external int a;

  @ffi.Int()
  external int b;

  @ffi.Int()
  external int c;

  static ffi.Pointer<Struct3> $allocate(
    ffi.Allocator $allocator, {
    required int a,
    required int b,
    required int c,
  }) => $allocator<Struct3>()
    ..ref.a = a
    ..ref.b = b
    ..ref.c = c;
}

final class StructWithEnums extends ffi.Struct {
  @ffi.UnsignedInt()
  external int enum1AsInt;

  Enum1 get enum1 => Enum1.fromValue(enum1AsInt);
  set enum1(Enum1 value) => enum1AsInt = value.value;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.UnsignedInt> enum1Array;

  external ffi.Pointer<ffi.UnsignedInt> enum1Pointer;

  @ffi.UnsignedInt()
  external int enum2;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.UnsignedInt> enum2Array;

  external ffi.Pointer<ffi.UnsignedInt> enum2Pointer;
}
